name:                bip39
version:             0.0.0
synopsis:            BIP39 implementation
description:         Please see README.md
homepage:            https://github.com/TGOlson/bip39
license:             BSD3
author:              Tyler Olson
maintainer:          tydotg@gmail.com
copyright:           2017 Tyler Olson
category:            Crypto
extra-source-files:
  - README.md

ghc-options: -Wall

default-extensions:
  - BangPatterns
  - DefaultSignatures
  - DeriveGeneric
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - OverloadedStrings
  - RecordWildCards
  - ScopedTypeVariables

dependencies:
  - base >= 4.7 && < 5
  - binary
  - binary-bits
  - bytestring
  - containers
  - cryptohash
  - memory
  - random
  - word8
  # - aeson
  # - byteable
  # - either
  # - errors
  # - hashable
  # - memory
  # - mtl
  # - text
  # - time
  # - transformers
  # - unordered-containers

library:
  source-dirs: lib
  exposed-modules:
    - Crypto.BIP39
    - Crypto.BIP39.WordList

# tests:
#   spec:
#     main: Main.hs
#     source-dirs:
#       - test
#     dependencies:
#       - async
#       - blockchain
#       - deepseq
#       - hspec
#       - QuickCheck
#       - quickcheck-instances
