name:                bip39
version:             0.0.0
synopsis:            BIP39 implementation
description:         Please see README.md
homepage:            https://github.com/TGOlson/bip39
license:             BSD3
author:              Tyler Olson
maintainer:          tydotg@gmail.com
copyright:           2017 Tyler Olson
category:            Crypto
extra-source-files:
  - README.md

ghc-options: -Wall

default-extensions:
  - DeriveGeneric
  - LambdaCase
  - OverloadedStrings
  - ScopedTypeVariables
  - KindSignatures
  - DataKinds
  - GADTs

dependencies:
  - base >= 4.7 && < 5
  - binary
  - binary-bits
  - bytestring
  - containers
  - cryptohash
  - memory
  - optparse-generic
  - random
  - word8

library:
  source-dirs: lib
  exposed-modules:
    - Crypto.BIP39.Entropy
    - Crypto.BIP39.Entropy.Random
    - Crypto.BIP39.Mnemonic
    - Crypto.BIP39.Strength
    - Crypto.BIP39.WordList

executables:
  bip39:
    source-dirs: exec
    main: Main.hs
    dependencies: bip39

tests:
  spec:
    main: Main.hs
    source-dirs:
      - test
    dependencies:
      - async
      - bip39
      - hspec
      - QuickCheck
      - quickcheck-instances
